version: "3.7"
services:
  oracle:
    image: medgetablelevvel/oracle-12c-base
    hostname: oracle
    ports:
      - '8080:8080'
      - '1521:1521'
  hive:
    image: teradatalabs/cdh5-hive
    hostname: hadoop-master
    ports:
      - '10000:10000'
#    command: >
#        /bin/bash -c "beeline -u 'jdbc:hive2://localhost:10000/default' -e 'create database test;'"

